ARG NODE_MAJOR_VERSION
FROM bearstech/node:${NODE_MAJOR_VERSION}

ARG YARN_VERSION
LABEL com.bearstech.version.yarn=${YARN_VERSION}

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo 'deb https://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y \
        yarn \
        python2.7 \
        make \
        build-essential \
        git \
        mercurial \
    && rm -rf /var/lib/apt/lists/*
RUN npm install -g node-gyp
