ARG NODE_MAJOR_VERSION
FROM bearstech/node:${NODE_MAJOR_VERSION}

ARG YARN_VERSION
LABEL com.bearstech.version.yarn=${YARN_VERSION}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN set -eux \
    &&  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    &&  echo 'deb https://dl.yarnpkg.com/debian/ stable main' | tee /etc/apt/sources.list.d/yarn.list \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                yarn \
                python2.7 \
                make \
                build-essential \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  npm install -g node-gyp

SHELL ["/bin/sh", "-c"]
